title: "Engineering Log"
description: "프로젝트, 기술 탐구, 공부 내용을 한 데 모은 개인 기록 저장소"
url: "https://hyunwoopark-dev.github.io" # 본인 주소
baseurl: "/HyunwooPark.github.io"

minimal_mistakes_skin: "default"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
