title: "Engineering Log"
description: "프로젝트, 기술 탐구, 공부 내용을 한 데 모은 개인 기록 저장소"
url: "https://hyunwoopark-dev.github.io" # 본인 github.io 주소
baseurl: "/HyunwooPark.github.io"

# GitHub Pages용 Minimal Mistakes 테마적용
remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
